
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TehKonnos ;)
 */
public class ATM extends javax.swing.JFrame {

    /**
     * Creates new form ATM
     */
    int xt;
    int money[]= {0,0,0,0,0,0,0,0};
    public ATM() {
        
        
        this.setUndecorated(true);
        initComponents();
        this.setResizable(false);
        
        this.setVisible(true);
        
         this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
         
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pin = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        ok2 = new javax.swing.JButton();
        akirosi1 = new javax.swing.JButton();
        lathos = new javax.swing.JLabel();
        txtpin = new javax.swing.JPasswordField();
        Epiloges = new javax.swing.JFrame();
        katathesi = new javax.swing.JButton();
        labonoma = new javax.swing.JLabel();
        Analipsi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        exodos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        mls = new javax.swing.JLabel();
        last = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        οκ3 = new javax.swing.JButton();
        anal = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        kata = new javax.swing.JFrame();
        epistrofi2 = new javax.swing.JButton();
        txtm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        done = new javax.swing.JButton();
        telos = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        epistr2 = new javax.swing.JButton();
        creator = new javax.swing.JFrame();
        jLabel13 = new javax.swing.JLabel();
        kys = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ok1 = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();

        pin.setBackground(new java.awt.Color(204, 0, 153));
        pin.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Παρακαλώ εισάγετε το PIN της κάρτας σας");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 31, 0);
        pin.getContentPane().add(jLabel2, gridBagConstraints);

        ok2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ok2.setText("OK");
        ok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 68;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.9;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 31, 0);
        pin.getContentPane().add(ok2, gridBagConstraints);

        akirosi1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        akirosi1.setText("ΑΚΥΡΩΣΗ");
        akirosi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akirosi1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 60);
        pin.getContentPane().add(akirosi1, gridBagConstraints);

        lathos.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pin.getContentPane().add(lathos, gridBagConstraints);

        txtpin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(24, 24, 24, 24);
        pin.getContentPane().add(txtpin, gridBagConstraints);

        Epiloges.getContentPane().setLayout(new java.awt.GridBagLayout());

        katathesi.setText("ΚΑΤΑΘΕΣΗ");
        katathesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                katathesiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(36, 0, 36, 0);
        Epiloges.getContentPane().add(katathesi, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        Epiloges.getContentPane().add(labonoma, gridBagConstraints);

        Analipsi.setText("ΑΝΑΛΗΨΗ");
        Analipsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalipsiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(36, 0, 36, 0);
        Epiloges.getContentPane().add(Analipsi, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Παρακαλώ διαλέξτε μία από τις παρακάτω επιλογές:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Epiloges.getContentPane().add(jLabel4, gridBagConstraints);

        exodos.setText("ΕΞΟΔΟΣ");
        exodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exodosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 0, 44, 0);
        Epiloges.getContentPane().add(exodos, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Διαθέσιμο υπόλοιπο:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(23, 0, 23, 0);
        Epiloges.getContentPane().add(jLabel6, gridBagConstraints);

        mls.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mls.setText("0$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        Epiloges.getContentPane().add(mls, gridBagConstraints);

        last.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ΕΥΧΑΡΙΣΤΟΥΜΕ ΠΟΥ ΧΡΗΣΗΜΟΠΟΙΗΣΑΤΕ ΤΗΝ ΤΡΑΠΕΖΑ ΜΑΣ!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        last.getContentPane().add(jLabel3, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("ΚΑΛΗ ΣΥΝΕΧΕΙΑ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        last.getContentPane().add(jLabel5, gridBagConstraints);

        οκ3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        οκ3.setText("ΟΚ");
        οκ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                οκ3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        last.getContentPane().add(οκ3, gridBagConstraints);

        anal.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Λυπούμαστε, αλλά αυτή την στιγμή είναι αδύνατη η ανάληψη χρημάτων.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 0);
        anal.getContentPane().add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Παρακαλούμε επισκεφθείτε μία τράπεζα κοντά σας.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 0);
        anal.getContentPane().add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Εκ μέρους όλης της τράπεζας συγγνωμη για την καθυστέριση.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(37, 0, 0, 0);
        anal.getContentPane().add(jLabel10, gridBagConstraints);

        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setText("Επιστροφή");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(41, 0, 0, 0);
        anal.getContentPane().add(back, gridBagConstraints);

        kata.getContentPane().setLayout(new java.awt.GridBagLayout());

        epistrofi2.setText("Επιστροφή");
        epistrofi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epistrofi2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(22, 22, 22, 22);
        kata.getContentPane().add(epistrofi2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        kata.getContentPane().add(txtm, gridBagConstraints);

        jLabel7.setText("Παρακαλώ δώσε ποσό χρημάτων:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(34, 22, 34, 22);
        kata.getContentPane().add(jLabel7, gridBagConstraints);

        done.setText("Έγινε!");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(22, 22, 22, 22);
        kata.getContentPane().add(done, gridBagConstraints);

        telos.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Παρακαλώ καταθέστε τα χρήματα στην ειδική εσοχή.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(29, 11, 6, 29);
        telos.getContentPane().add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Ευχαριστουμε που επιλέξατε την τράπεζα μας. Καλή συνέχεια!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(11, 34, 11, 11);
        telos.getContentPane().add(jLabel12, gridBagConstraints);

        epistr2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        epistr2.setText("Επιστροφή");
        epistr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epistr2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(26, 0, 0, 0);
        telos.getContentPane().add(epistr2, gridBagConstraints);

        creator.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("MADE BY TEHKONNOS");
        creator.getContentPane().add(jLabel13, new java.awt.GridBagConstraints());

        kys.setBackground(new java.awt.Color(255, 51, 51));
        kys.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kys.setForeground(new java.awt.Color(0, 204, 204));
        kys.setText("KYS");
        kys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kysActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        creator.getContentPane().add(kys, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ΑΤΜ");
        setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Παρακαλώ εισάγετε την κάρτα σας");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel1, gridBagConstraints);

        ok1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ok1.setText("ΟΚ");
        ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 68;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 21);
        getContentPane().add(ok1, gridBagConstraints);

        EXIT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EXIT.setText("ΕΞΟΔΟΣ");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(115, 128, 109, 0);
        getContentPane().add(EXIT, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok1ActionPerformed
        xt=0;
        txtpin.setText("");
        lathos.setText("");
        pin.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        pin.setUndecorated(true);
         pin.setVisible(true);
    }//GEN-LAST:event_ok1ActionPerformed

    private void akirosi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akirosi1ActionPerformed
        pin.dispose();
    }//GEN-LAST:event_akirosi1ActionPerformed
    String name;
    int n;
    private void ok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok2ActionPerformed
        int t = Integer.valueOf(txtpin.getText());
        if(t==1111){
            name="Guest";
            n=0;
            mls.setText(String.valueOf(money[n]+"€"));
            labonoma.setText("Καλώς όρισες, "+name);
            Epiloges.setExtendedState(JFrame.MAXIMIZED_BOTH); 
            Epiloges.setUndecorated(true);
            pin.dispose();
            Epiloges.setVisible(true);
        }else if(t==8862){
            
            name="Μπλέ κάρτα";
            n=1;
            mls.setText(String.valueOf(money[n]+"€"));
            labonoma.setText("Καλώς όρισες, "+name);
            Epiloges.setExtendedState(JFrame.MAXIMIZED_BOTH); 
            Epiloges.setUndecorated(true);
            pin.dispose();
            Epiloges.setVisible(true);
        }else if(t==3741){
            
            name="Πράσινη κάρτα";
            n=2;
            mls.setText(String.valueOf(money[n]+"€"));
            labonoma.setText("Καλώς όρισες, "+name);
            Epiloges.setExtendedState(JFrame.MAXIMIZED_BOTH); 
            Epiloges.setUndecorated(true);
            pin.dispose();
            Epiloges.setVisible(true);
        
        }else if(t==1998){
            
            name="Πορτοκαλί κάρτα";
            n=3;
            mls.setText(String.valueOf(money[n]+"€"));
            labonoma.setText("Καλώς όρισες, "+name);
            Epiloges.setExtendedState(JFrame.MAXIMIZED_BOTH); 
            Epiloges.setUndecorated(true);
            pin.dispose();
            Epiloges.setVisible(true);
    
    
    }else if(t==7207){
            
            name="Μοβ κάρτα";
            n=4;
            mls.setText(String.valueOf(money[n]+"€"));
            labonoma.setText("Καλώς όρισες, "+name);
            Epiloges.setExtendedState(JFrame.MAXIMIZED_BOTH); 
            Epiloges.setUndecorated(true);
            pin.dispose();
            Epiloges.setVisible(true);
    }else if(t==1650){
            
            name="Κόκκινη κάρτα";
            n=5;
            mls.setText(String.valueOf(money[n]+"€"));
            labonoma.setText("Καλώς όρισες, "+name);
            Epiloges.setExtendedState(JFrame.MAXIMIZED_BOTH); 
            Epiloges.setUndecorated(true);
            pin.dispose();
            Epiloges.setVisible(true);
    
    }else if(t==3947){
            
            name="Κίτρινη κάρτα";
            n=6;
            mls.setText(String.valueOf(money[n]+"€"));
            labonoma.setText("Καλώς όρισες, "+name);
            Epiloges.setExtendedState(JFrame.MAXIMIZED_BOTH); 
            Epiloges.setUndecorated(true);
            pin.dispose();
            Epiloges.setVisible(true);
    }else if(t==1267){
            
            name="Ρατατούι";
            n=7;
            mls.setText(String.valueOf(money[n]+"€"));
            labonoma.setText("Καλώς όρισες, "+name);
            Epiloges.setExtendedState(JFrame.MAXIMIZED_BOTH); 
            Epiloges.setUndecorated(true);
            pin.dispose();
            Epiloges.setVisible(true);
            
    } else{   
            txtpin.setText("");
            lathos.setText("Προσοχή! Λάθος κωδικός PIN");
        }
    }//GEN-LAST:event_ok2ActionPerformed

    private void οκ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_οκ3ActionPerformed
       last.dispose();
    }//GEN-LAST:event_οκ3ActionPerformed

    private void exodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exodosActionPerformed
        last.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        last.setUndecorated(true);
        Epiloges.dispose();
        last.setVisible(true);
       
      
        
        
    }//GEN-LAST:event_exodosActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
          xt++;
          if(xt==3){
              System.exit(0);
          }
  
    }//GEN-LAST:event_EXITActionPerformed

    private void AnalipsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalipsiActionPerformed
       anal.setExtendedState(JFrame.MAXIMIZED_BOTH); 
       anal.setUndecorated(true);
       anal.setVisible(true);
    }//GEN-LAST:event_AnalipsiActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        anal.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void epistrofi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epistrofi2ActionPerformed
       mls.setText(String.valueOf(money[n]+"€"));
        kata.dispose();
    }//GEN-LAST:event_epistrofi2ActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
       telos.setExtendedState(JFrame.MAXIMIZED_BOTH); 
       telos.setUndecorated(true);
       telos.setVisible(true);
       money[n]+=Integer.valueOf(txtm.getText());
    }//GEN-LAST:event_doneActionPerformed

    private void epistr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epistr2ActionPerformed
        //txtm.setText("");
        telos.dispose();
        txtm.setText("");
        money[n]+=Integer.valueOf(txtm.getText());
    }//GEN-LAST:event_epistr2ActionPerformed

    private void katathesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_katathesiActionPerformed
       
       kata.setExtendedState(JFrame.MAXIMIZED_BOTH); 
       kata.setUndecorated(true);
       kata.setVisible(true);
      
    }//GEN-LAST:event_katathesiActionPerformed

    private void kysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kysActionPerformed
     System.exit(0);
    }//GEN-LAST:event_kysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ATM().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analipsi;
    private javax.swing.JButton EXIT;
    private javax.swing.JFrame Epiloges;
    private javax.swing.JButton akirosi1;
    private javax.swing.JFrame anal;
    private javax.swing.JButton back;
    private javax.swing.JFrame creator;
    private javax.swing.JButton done;
    private javax.swing.JButton epistr2;
    private javax.swing.JButton epistrofi2;
    private javax.swing.JButton exodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFrame kata;
    private javax.swing.JButton katathesi;
    private javax.swing.JButton kys;
    private javax.swing.JLabel labonoma;
    private javax.swing.JFrame last;
    private javax.swing.JLabel lathos;
    private javax.swing.JLabel mls;
    private javax.swing.JButton ok1;
    private javax.swing.JButton ok2;
    private javax.swing.JFrame pin;
    private javax.swing.JFrame telos;
    private javax.swing.JTextField txtm;
    private javax.swing.JPasswordField txtpin;
    private javax.swing.JButton οκ3;
    // End of variables declaration//GEN-END:variables
}
